//USER ACTION TYPES
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = "GET_USERS"
export const GET_ALL_TEACHERS = "GET_TEACHERS";
export const GET_ALL_STUDENTS = "GET_STUDENTS";
export const GET_ONE_USER = "GET_ONE_USER";
export const PWD_RESET_HASH_CREATED = "PWD_RESET_HASH_CREATED";
export const PWD_RESET_HASH_FAILURE = "PWD_RESET_HASH_FAILURE";
export const PWD_RESET_CLEAR = "PWD_RESET_CLEAR";
export const PWD_SAVE_FAILURE = "PWD_SAVE_FAILURE";
export const PWD_SAVE_SUCCESS = "PWD_SAVE_SUCCESS";
export const GET_ALL_USERS = "GET_ALL_USERS"

//CLASSES ACTION TYPES
export const GET_CLASSES = "GET_CLASSES";
export const ADDED_CLASSES = "ADDED_CLASSES";
export const CLASSES_LOADING = "CLASSES_LOADING";
export const GET_ALL_CLASSES = "GET_ALL_CLASSES";
export const SET_CURRENT_CLASS = "SET_CURRENT_CLASS";

// TASK ACTION TYPES
export const GET_TASKS = "GET_TASKS";
export const TASKS_LOADING = "TASKS_LOADING";
export const GET_TASKS_BY_CLASS = "GET_TASKS_BY_CLASS";
export const GET_TASKS_BY_SUBJECTS = "GET_TASKS_BY_SUBJECTS";
export const GRADE_TASKS = "GRADE_TASKS"

//ERROR ACTION TYPES
export const GET_ERRORS = "GET_ERRORS";
export const UPDATE_ERRORS = "UPDATE_ERRORS";

//SUCCESS ACTION TYPES
export const GET_SUCCESS_RESPONSE = "GET_SUCCESS_RESPONSE";

//UPLOAD ACTION TYPES
//TASK_FILES ACTION TYPES
//ANNOUNCEMENT_LAMPIRAN ACTIOn TYPES
export const GET_FILE_BY_USER = "GET_FILE_BY_USER";
export const GET_ALL_FILES_BY_USER = "GET_ALL_FILES_BY_USER"
export const UPLOAD_TUGAS = "UPLOAD_TUGAS"
export const GET_TUGAS = "GET_TUGAS"
export const GET_LAMPIRAN_FILES = "GET_LAMPIRAN_FILES";
export const GET_ALL_LAMPIRAN_BY_TASK = "GET_ALL_LAMPIRAN_BY_TASK";

//SUBJECT ACTION TYPES
export const GET_SUBJECT = "GET_SUBJECT";
export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECT";

//Material Action types
export const GET_MATERIAL = "GET_MATERIAL"
export const GET_ALL_MATERIALS = "GET_ALL_MATERIALS"
export const SUCCESS_MATERIAL = "SUCCESS_MATERIAL"

//Announcement action types
export const GET_ANNOUNCEMENT = "GET_ANNOUNCEMENT";
export const GET_ALL_ANNOUNCEMENTS = "GET_ALL_ANNOUNCEMENTS"
