//AUTHENTICATION ACTION TYPES
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = "GET_USERS"

//CLASSES ACTION TYPES
export const GET_CLASSES = "GET_CLASSES";
export const ADDED_CLASSES = "ADDED_CLASSES";
export const CLASSES_LOADING = "CLASSES_LOADING";

// TASK ACTION TYPES
export const GET_TASKS = "GET_TASKS";
export const ADD_TASKS = "ADD_TASKS";
export const TASKS_LOADING = "TASKS_LOADING";

//ERROR ACTION TYPES
export const GET_ERRORS = "GET_ERRORS";