// USER ACTION TYPES
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_MY_AVATAR = "GET_MY_AVATAR";
export const GET_USERS = "GET_USERS";
export const GET_ONE_USER = "GET_ONE_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_ADMINS = "GET_ALL_ADMINS";
export const GET_ALL_TEACHERS = "GET_TEACHERS";
export const GET_ALL_TEACHERS_MAP = "GET_TEACHERS_MAP";
export const GET_ALL_STUDENTS = "GET_STUDENTS";
export const GET_STUDENTS_BY_CLASS = "GET_STUDENTS_BY_CLASS";
export const GET_PENDING_ADMINS = "GET_PENDING_ADMINS";
export const GET_PENDING_TEACHERS = "GET_PENDING_TEACHERS";
export const GET_PENDING_STUDENTS = "GET_PENDING_STUDENTS";
export const GET_REGISTER_ERRORS = "GET_REGISTER_ERRORS";
export const PWD_RESET_HASH_CREATED = "PWD_RESET_HASH_CREATED";
export const PWD_RESET_HASH_FAILURE = "PWD_RESET_HASH_FAILURE";
export const PWD_RESET_CLEAR = "PWD_RESET_CLEAR";
export const PWD_SAVE_SUCCESS = "PWD_SAVE_SUCCESS";
export const PWD_SAVE_FAILURE = "PWD_SAVE_FAILURE";

// UNIT ACTION TYPES
export const GET_UNIT = "GET_UNIT";
export const GET_ALL_UNITS = "GET_ALL_UNITS";

// EVENT ACTION TYPES
export const GET_EVENT = "GET_EVENT";
export const GET_ALL_EVENTS = "GET_ALL_EVENTS";

// CLASSES ACTION TYPES
export const GET_CLASSES = "GET_CLASSES";
export const ADDED_CLASSES = "ADDED_CLASSES";
export const CLASSES_LOADING = "CLASSES_LOADING";
export const GET_ALL_CLASSES = "GET_ALL_CLASSES";
export const GET_ALL_CLASSES_MAP = "GET_ALL_CLASSES_MAP";
export const SET_CURRENT_CLASS = "SET_CURRENT_CLASS";
export const GET_SCHOOL_CLASSES = "GET_SCHOOL_CLASSES";

// SUBJECT ACTION TYPES
export const GET_SUBJECT = "GET_SUBJECT";
export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECT";
export const GET_ALL_SUBJECTS_MAP = "GET_ALL_SUBJECTS_MAP";

// ANNOUNCEMENT ACTION TYPES
export const GET_ANNOUNCEMENT = "GET_ANNOUNCEMENT";
export const GET_ALL_ANNOUNCEMENTS = "GET_ALL_ANNOUNCEMENTS";
export const GET_ADMIN_ANNOUNCEMENTS = "GET_ADMIN_ANNOUNCEMENTS";

// MATERIAL ACTION TYPES
export const GET_MATERIAL = "GET_MATERIAL";
export const GET_ALL_MATERIALS = "GET_ALL_MATERIALS";
export const SUCCESS_MATERIAL = "SUCCESS_MATERIAL";

// TASK ACTION TYPES
export const GET_ALL_TASKS = "GET_ALL_TASKS";
export const TASKS_LOADING = "TASKS_LOADING";
// export const GET_TASKS_BY_CLASS = "GET_TASKS_BY_CLASS";
export const GET_TASKS_BY_SUBJECTS = "GET_TASKS_BY_SUBJECTS";
export const GRADE_TASKS = "GRADE_TASKS";

// ASSESSMENT ACTION TYPES
export const GET_ASSESSMENT = "GET_ASSESSMENT";
export const GET_ALL_ASSESSMENTS = "GET_ALL_ASSESSMENTS";

// SETTING ACTION TYPES
export const GET_SETTING = "GET_SETTING";

// SUCCESS ACTION TYPES
export const GET_SUCCESS_RESPONSE = "GET_SUCCESS_RESPONSE";
export const CLEAR_SUCCESS_RESPONSE = "CLEAR_SUCCESS_RESPONSE";

// ERROR ACTION TYPES
export const GET_ERRORS = "GET_ERRORS";
export const UPDATE_ERRORS = "UPDATE_ERRORS";

// Files
// ANNOUNCEMENT FILES ACTION TYPES
export const GET_ANNOUNCEMENT_FILES = "GET_ANNOUNCEMENT_FILES";
export const GET_ALL_ANNOUNCEMENT_FILES = "GET_ANNOUNCEMENT_FILES";

// MATERIAL FILES ACTION TYPES
export const GET_MATERIAL_FILES = "GET_MATERIAL_FILES";
export const GET_ALL_MATERIAL_FILES = "GET_ALL_MATERIAL_FILES";

// TASK FILES ACTION TYPES
export const UPLOAD_TUGAS = "UPLOAD_TUGAS";
export const GET_TUGAS = "GET_TUGAS";
export const GET_ALL_LAMPIRAN_BY_TASK = "GET_ALL_LAMPIRAN_BY_TASK";
export const GET_LAMPIRAN_FILES = "GET_LAMPIRAN_FILES";
export const GET_FILE_BY_USER = "GET_FILE_BY_USER";
export const GET_ALL_FILES_BY_USER = "GET_ALL_FILES_BY_USER";

// APIs
// DROPBOX ACTION TYPES
export const SET_DROPBOX_TOKEN = "SET_DROPBOX_TOKEN";
