const { ObjectId } = require("mongodb"); // API from mongoose MongoDB
const mongoose = require("mongoose"); // Require Mongoose
const Schema = mongoose.Schema; // Define a Schema

// Create Material Schema
const MaterialSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      required: true,
    },
    unit: {
      type: ObjectId,
      default: null,
    },
    class_assigned: [
      {
        type: ObjectId,
        required: true,
      },
    ],
    subject: {
      type: ObjectId,
      required: true,
    },
    author_id: {
      type: ObjectId,
      required: true,
    },
    lampiran: [
      {
        type: Object,
        default: [],
      },
    ],
    comments: [
      {
        // "_id" attribute value (that is generated by default) will be used to edit or delete comment.
        author_id: {
          type: ObjectId,
          required: true,
        },
        content: {
          type: String,
          required: true,
        },
        edited: {
          type: Boolean,
          default: false,
        },
        createdAt: {
          type: Date,
          required: true,
        },
      },
    ],
  },
  { timestamps: true }
);

module.exports = Material = mongoose.model("materials", MaterialSchema);
